package com.qlml.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LoginUserExample {
      protected String orderByClause;

      protected boolean distinct;

      protected List<Criteria> oredCriteria;

      public LoginUserExample() {
            oredCriteria = new ArrayList<Criteria>();
      }

      public void setOrderByClause(String orderByClause) {
            this.orderByClause = orderByClause;
      }

      public String getOrderByClause() {
            return orderByClause;
      }

      public void setDistinct(boolean distinct) {
            this.distinct = distinct;
      }

      public boolean isDistinct() {
            return distinct;
      }

      public List<Criteria> getOredCriteria() {
            return oredCriteria;
      }

      public void or(Criteria criteria) {
            oredCriteria.add(criteria);
      }

      public Criteria or() {
            Criteria criteria = createCriteriaInternal();
            oredCriteria.add(criteria);
            return criteria;
      }

      public Criteria createCriteria() {
            Criteria criteria = createCriteriaInternal();
            if (oredCriteria.size() == 0) {
                  oredCriteria.add(criteria);
            }
            return criteria;
      }

      protected Criteria createCriteriaInternal() {
            Criteria criteria = new Criteria();
            return criteria;
      }

      public void clear() {
            oredCriteria.clear();
            orderByClause = null;
            distinct = false;
      }

      /**
       * This class was generated by MyBatis Generator.
       * This class corresponds to the database table login_user
       *
       * @mbggenerated
       */
      protected abstract static class GeneratedCriteria {
            protected List<Criterion> criteria;

            protected GeneratedCriteria() {
                  super();
                  criteria = new ArrayList<Criterion>();
            }

            public boolean isValid() {
                  return criteria.size() > 0;
            }

            public List<Criterion> getAllCriteria() {
                  return criteria;
            }

            public List<Criterion> getCriteria() {
                  return criteria;
            }

            protected void addCriterion(String condition) {
                  if (condition == null) {
                        throw new RuntimeException("Value for condition cannot be null");
                  }
                  criteria.add(new Criterion(condition));
            }

            protected void addCriterion(String condition, Object value, String property) {
                  if (value == null) {
                        throw new RuntimeException("Value for " + property + " cannot be null");
                  }
                  criteria.add(new Criterion(condition, value));
            }

            protected void addCriterion(String condition, Object value1, Object value2, String property) {
                  if (value1 == null || value2 == null) {
                        throw new RuntimeException("Between values for " + property + " cannot be null");
                  }
                  criteria.add(new Criterion(condition, value1, value2));
            }

            public Criteria andUserIdIsNull() {
                  addCriterion("user_id is null");
                  return (Criteria) this;
            }

            public Criteria andUserIdIsNotNull() {
                  addCriterion("user_id is not null");
                  return (Criteria) this;
            }

            public Criteria andUserIdEqualTo(Integer value) {
                  addCriterion("user_id =", value, "userId");
                  return (Criteria) this;
            }

            public Criteria andUserIdNotEqualTo(Integer value) {
                  addCriterion("user_id <>", value, "userId");
                  return (Criteria) this;
            }

            public Criteria andUserIdGreaterThan(Integer value) {
                  addCriterion("user_id >", value, "userId");
                  return (Criteria) this;
            }

            public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
                  addCriterion("user_id >=", value, "userId");
                  return (Criteria) this;
            }

            public Criteria andUserIdLessThan(Integer value) {
                  addCriterion("user_id <", value, "userId");
                  return (Criteria) this;
            }

            public Criteria andUserIdLessThanOrEqualTo(Integer value) {
                  addCriterion("user_id <=", value, "userId");
                  return (Criteria) this;
            }

            public Criteria andUserIdIn(List<Integer> values) {
                  addCriterion("user_id in", values, "userId");
                  return (Criteria) this;
            }

            public Criteria andUserIdNotIn(List<Integer> values) {
                  addCriterion("user_id not in", values, "userId");
                  return (Criteria) this;
            }

            public Criteria andUserIdBetween(Integer value1, Integer value2) {
                  addCriterion("user_id between", value1, value2, "userId");
                  return (Criteria) this;
            }

            public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
                  addCriterion("user_id not between", value1, value2, "userId");
                  return (Criteria) this;
            }

            public Criteria andLoginNameIsNull() {
                  addCriterion("login_name is null");
                  return (Criteria) this;
            }

            public Criteria andLoginNameIsNotNull() {
                  addCriterion("login_name is not null");
                  return (Criteria) this;
            }

            public Criteria andLoginNameEqualTo(String value) {
                  addCriterion("login_name =", value, "loginName");
                  return (Criteria) this;
            }

            public Criteria andLoginNameNotEqualTo(String value) {
                  addCriterion("login_name <>", value, "loginName");
                  return (Criteria) this;
            }

            public Criteria andLoginNameGreaterThan(String value) {
                  addCriterion("login_name >", value, "loginName");
                  return (Criteria) this;
            }

            public Criteria andLoginNameGreaterThanOrEqualTo(String value) {
                  addCriterion("login_name >=", value, "loginName");
                  return (Criteria) this;
            }

            public Criteria andLoginNameLessThan(String value) {
                  addCriterion("login_name <", value, "loginName");
                  return (Criteria) this;
            }

            public Criteria andLoginNameLessThanOrEqualTo(String value) {
                  addCriterion("login_name <=", value, "loginName");
                  return (Criteria) this;
            }

            public Criteria andLoginNameLike(String value) {
                  addCriterion("login_name like", value, "loginName");
                  return (Criteria) this;
            }

            public Criteria andLoginNameNotLike(String value) {
                  addCriterion("login_name not like", value, "loginName");
                  return (Criteria) this;
            }

            public Criteria andLoginNameIn(List<String> values) {
                  addCriterion("login_name in", values, "loginName");
                  return (Criteria) this;
            }

            public Criteria andLoginNameNotIn(List<String> values) {
                  addCriterion("login_name not in", values, "loginName");
                  return (Criteria) this;
            }

            public Criteria andLoginNameBetween(String value1, String value2) {
                  addCriterion("login_name between", value1, value2, "loginName");
                  return (Criteria) this;
            }

            public Criteria andLoginNameNotBetween(String value1, String value2) {
                  addCriterion("login_name not between", value1, value2, "loginName");
                  return (Criteria) this;
            }

            public Criteria andStatusIsNull() {
                  addCriterion("status is null");
                  return (Criteria) this;
            }

            public Criteria andStatusIsNotNull() {
                  addCriterion("status is not null");
                  return (Criteria) this;
            }

            public Criteria andStatusEqualTo(Integer value) {
                  addCriterion("status =", value, "status");
                  return (Criteria) this;
            }

            public Criteria andStatusNotEqualTo(Integer value) {
                  addCriterion("status <>", value, "status");
                  return (Criteria) this;
            }

            public Criteria andStatusGreaterThan(Integer value) {
                  addCriterion("status >", value, "status");
                  return (Criteria) this;
            }

            public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
                  addCriterion("status >=", value, "status");
                  return (Criteria) this;
            }

            public Criteria andStatusLessThan(Integer value) {
                  addCriterion("status <", value, "status");
                  return (Criteria) this;
            }

            public Criteria andStatusLessThanOrEqualTo(Integer value) {
                  addCriterion("status <=", value, "status");
                  return (Criteria) this;
            }

            public Criteria andStatusIn(List<Integer> values) {
                  addCriterion("status in", values, "status");
                  return (Criteria) this;
            }

            public Criteria andStatusNotIn(List<Integer> values) {
                  addCriterion("status not in", values, "status");
                  return (Criteria) this;
            }

            public Criteria andStatusBetween(Integer value1, Integer value2) {
                  addCriterion("status between", value1, value2, "status");
                  return (Criteria) this;
            }

            public Criteria andStatusNotBetween(Integer value1, Integer value2) {
                  addCriterion("status not between", value1, value2, "status");
                  return (Criteria) this;
            }

            public Criteria andOrgIdIsNull() {
                  addCriterion("org_id is null");
                  return (Criteria) this;
            }

            public Criteria andOrgIdIsNotNull() {
                  addCriterion("org_id is not null");
                  return (Criteria) this;
            }

            public Criteria andOrgIdEqualTo(Integer value) {
                  addCriterion("org_id =", value, "orgId");
                  return (Criteria) this;
            }

            public Criteria andOrgIdNotEqualTo(Integer value) {
                  addCriterion("org_id <>", value, "orgId");
                  return (Criteria) this;
            }

            public Criteria andOrgIdGreaterThan(Integer value) {
                  addCriterion("org_id >", value, "orgId");
                  return (Criteria) this;
            }

            public Criteria andOrgIdGreaterThanOrEqualTo(Integer value) {
                  addCriterion("org_id >=", value, "orgId");
                  return (Criteria) this;
            }

            public Criteria andOrgIdLessThan(Integer value) {
                  addCriterion("org_id <", value, "orgId");
                  return (Criteria) this;
            }

            public Criteria andOrgIdLessThanOrEqualTo(Integer value) {
                  addCriterion("org_id <=", value, "orgId");
                  return (Criteria) this;
            }

            public Criteria andOrgIdIn(List<Integer> values) {
                  addCriterion("org_id in", values, "orgId");
                  return (Criteria) this;
            }

            public Criteria andOrgIdNotIn(List<Integer> values) {
                  addCriterion("org_id not in", values, "orgId");
                  return (Criteria) this;
            }

            public Criteria andOrgIdBetween(Integer value1, Integer value2) {
                  addCriterion("org_id between", value1, value2, "orgId");
                  return (Criteria) this;
            }

            public Criteria andOrgIdNotBetween(Integer value1, Integer value2) {
                  addCriterion("org_id not between", value1, value2, "orgId");
                  return (Criteria) this;
            }

            public Criteria andFullNameIsNull() {
                  addCriterion("full_name is null");
                  return (Criteria) this;
            }

            public Criteria andFullNameIsNotNull() {
                  addCriterion("full_name is not null");
                  return (Criteria) this;
            }

            public Criteria andFullNameEqualTo(String value) {
                  addCriterion("full_name =", value, "fullName");
                  return (Criteria) this;
            }

            public Criteria andFullNameNotEqualTo(String value) {
                  addCriterion("full_name <>", value, "fullName");
                  return (Criteria) this;
            }

            public Criteria andFullNameGreaterThan(String value) {
                  addCriterion("full_name >", value, "fullName");
                  return (Criteria) this;
            }

            public Criteria andFullNameGreaterThanOrEqualTo(String value) {
                  addCriterion("full_name >=", value, "fullName");
                  return (Criteria) this;
            }

            public Criteria andFullNameLessThan(String value) {
                  addCriterion("full_name <", value, "fullName");
                  return (Criteria) this;
            }

            public Criteria andFullNameLessThanOrEqualTo(String value) {
                  addCriterion("full_name <=", value, "fullName");
                  return (Criteria) this;
            }

            public Criteria andFullNameLike(String value) {
                  addCriterion("full_name like", value, "fullName");
                  return (Criteria) this;
            }

            public Criteria andFullNameNotLike(String value) {
                  addCriterion("full_name not like", value, "fullName");
                  return (Criteria) this;
            }

            public Criteria andFullNameIn(List<String> values) {
                  addCriterion("full_name in", values, "fullName");
                  return (Criteria) this;
            }

            public Criteria andFullNameNotIn(List<String> values) {
                  addCriterion("full_name not in", values, "fullName");
                  return (Criteria) this;
            }

            public Criteria andFullNameBetween(String value1, String value2) {
                  addCriterion("full_name between", value1, value2, "fullName");
                  return (Criteria) this;
            }

            public Criteria andFullNameNotBetween(String value1, String value2) {
                  addCriterion("full_name not between", value1, value2, "fullName");
                  return (Criteria) this;
            }

            public Criteria andEmailIsNull() {
                  addCriterion("email is null");
                  return (Criteria) this;
            }

            public Criteria andEmailIsNotNull() {
                  addCriterion("email is not null");
                  return (Criteria) this;
            }

            public Criteria andEmailEqualTo(String value) {
                  addCriterion("email =", value, "email");
                  return (Criteria) this;
            }

            public Criteria andEmailNotEqualTo(String value) {
                  addCriterion("email <>", value, "email");
                  return (Criteria) this;
            }

            public Criteria andEmailGreaterThan(String value) {
                  addCriterion("email >", value, "email");
                  return (Criteria) this;
            }

            public Criteria andEmailGreaterThanOrEqualTo(String value) {
                  addCriterion("email >=", value, "email");
                  return (Criteria) this;
            }

            public Criteria andEmailLessThan(String value) {
                  addCriterion("email <", value, "email");
                  return (Criteria) this;
            }

            public Criteria andEmailLessThanOrEqualTo(String value) {
                  addCriterion("email <=", value, "email");
                  return (Criteria) this;
            }

            public Criteria andEmailLike(String value) {
                  addCriterion("email like", value, "email");
                  return (Criteria) this;
            }

            public Criteria andEmailNotLike(String value) {
                  addCriterion("email not like", value, "email");
                  return (Criteria) this;
            }

            public Criteria andEmailIn(List<String> values) {
                  addCriterion("email in", values, "email");
                  return (Criteria) this;
            }

            public Criteria andEmailNotIn(List<String> values) {
                  addCriterion("email not in", values, "email");
                  return (Criteria) this;
            }

            public Criteria andEmailBetween(String value1, String value2) {
                  addCriterion("email between", value1, value2, "email");
                  return (Criteria) this;
            }

            public Criteria andEmailNotBetween(String value1, String value2) {
                  addCriterion("email not between", value1, value2, "email");
                  return (Criteria) this;
            }

            public Criteria andCreateTimeIsNull() {
                  addCriterion("create_time is null");
                  return (Criteria) this;
            }

            public Criteria andCreateTimeIsNotNull() {
                  addCriterion("create_time is not null");
                  return (Criteria) this;
            }

            public Criteria andCreateTimeEqualTo(Date value) {
                  addCriterion("create_time =", value, "createTime");
                  return (Criteria) this;
            }

            public Criteria andCreateTimeNotEqualTo(Date value) {
                  addCriterion("create_time <>", value, "createTime");
                  return (Criteria) this;
            }

            public Criteria andCreateTimeGreaterThan(Date value) {
                  addCriterion("create_time >", value, "createTime");
                  return (Criteria) this;
            }

            public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
                  addCriterion("create_time >=", value, "createTime");
                  return (Criteria) this;
            }

            public Criteria andCreateTimeLessThan(Date value) {
                  addCriterion("create_time <", value, "createTime");
                  return (Criteria) this;
            }

            public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
                  addCriterion("create_time <=", value, "createTime");
                  return (Criteria) this;
            }

            public Criteria andCreateTimeIn(List<Date> values) {
                  addCriterion("create_time in", values, "createTime");
                  return (Criteria) this;
            }

            public Criteria andCreateTimeNotIn(List<Date> values) {
                  addCriterion("create_time not in", values, "createTime");
                  return (Criteria) this;
            }

            public Criteria andCreateTimeBetween(Date value1, Date value2) {
                  addCriterion("create_time between", value1, value2, "createTime");
                  return (Criteria) this;
            }

            public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
                  addCriterion("create_time not between", value1, value2, "createTime");
                  return (Criteria) this;
            }

            public Criteria andSystemAdminIsNull() {
                  addCriterion("system_admin is null");
                  return (Criteria) this;
            }

            public Criteria andSystemAdminIsNotNull() {
                  addCriterion("system_admin is not null");
                  return (Criteria) this;
            }

            public Criteria andSystemAdminEqualTo(Boolean value) {
                  addCriterion("system_admin =", value, "systemAdmin");
                  return (Criteria) this;
            }

            public Criteria andSystemAdminNotEqualTo(Boolean value) {
                  addCriterion("system_admin <>", value, "systemAdmin");
                  return (Criteria) this;
            }

            public Criteria andSystemAdminGreaterThan(Boolean value) {
                  addCriterion("system_admin >", value, "systemAdmin");
                  return (Criteria) this;
            }

            public Criteria andSystemAdminGreaterThanOrEqualTo(Boolean value) {
                  addCriterion("system_admin >=", value, "systemAdmin");
                  return (Criteria) this;
            }

            public Criteria andSystemAdminLessThan(Boolean value) {
                  addCriterion("system_admin <", value, "systemAdmin");
                  return (Criteria) this;
            }

            public Criteria andSystemAdminLessThanOrEqualTo(Boolean value) {
                  addCriterion("system_admin <=", value, "systemAdmin");
                  return (Criteria) this;
            }

            public Criteria andSystemAdminIn(List<Boolean> values) {
                  addCriterion("system_admin in", values, "systemAdmin");
                  return (Criteria) this;
            }

            public Criteria andSystemAdminNotIn(List<Boolean> values) {
                  addCriterion("system_admin not in", values, "systemAdmin");
                  return (Criteria) this;
            }

            public Criteria andSystemAdminBetween(Boolean value1, Boolean value2) {
                  addCriterion("system_admin between", value1, value2, "systemAdmin");
                  return (Criteria) this;
            }

            public Criteria andSystemAdminNotBetween(Boolean value1, Boolean value2) {
                  addCriterion("system_admin not between", value1, value2, "systemAdmin");
                  return (Criteria) this;
            }

            public Criteria andOrgLinksIsNull() {
                  addCriterion("org_links is null");
                  return (Criteria) this;
            }

            public Criteria andOrgLinksIsNotNull() {
                  addCriterion("org_links is not null");
                  return (Criteria) this;
            }

            public Criteria andOrgLinksEqualTo(String value) {
                  addCriterion("org_links =", value, "orgLinks");
                  return (Criteria) this;
            }

            public Criteria andOrgLinksNotEqualTo(String value) {
                  addCriterion("org_links <>", value, "orgLinks");
                  return (Criteria) this;
            }

            public Criteria andOrgLinksGreaterThan(String value) {
                  addCriterion("org_links >", value, "orgLinks");
                  return (Criteria) this;
            }

            public Criteria andOrgLinksGreaterThanOrEqualTo(String value) {
                  addCriterion("org_links >=", value, "orgLinks");
                  return (Criteria) this;
            }

            public Criteria andOrgLinksLessThan(String value) {
                  addCriterion("org_links <", value, "orgLinks");
                  return (Criteria) this;
            }

            public Criteria andOrgLinksLessThanOrEqualTo(String value) {
                  addCriterion("org_links <=", value, "orgLinks");
                  return (Criteria) this;
            }

            public Criteria andOrgLinksLike(String value) {
                  addCriterion("org_links like", value, "orgLinks");
                  return (Criteria) this;
            }

            public Criteria andOrgLinksNotLike(String value) {
                  addCriterion("org_links not like", value, "orgLinks");
                  return (Criteria) this;
            }

            public Criteria andOrgLinksIn(List<String> values) {
                  addCriterion("org_links in", values, "orgLinks");
                  return (Criteria) this;
            }

            public Criteria andOrgLinksNotIn(List<String> values) {
                  addCriterion("org_links not in", values, "orgLinks");
                  return (Criteria) this;
            }

            public Criteria andOrgLinksBetween(String value1, String value2) {
                  addCriterion("org_links between", value1, value2, "orgLinks");
                  return (Criteria) this;
            }

            public Criteria andOrgLinksNotBetween(String value1, String value2) {
                  addCriterion("org_links not between", value1, value2, "orgLinks");
                  return (Criteria) this;
            }

            public Criteria andWithOptionIsNull() {
                  addCriterion("with_option is null");
                  return (Criteria) this;
            }

            public Criteria andWithOptionIsNotNull() {
                  addCriterion("with_option is not null");
                  return (Criteria) this;
            }

            public Criteria andWithOptionEqualTo(Integer value) {
                  addCriterion("with_option =", value, "withOption");
                  return (Criteria) this;
            }

            public Criteria andWithOptionNotEqualTo(Integer value) {
                  addCriterion("with_option <>", value, "withOption");
                  return (Criteria) this;
            }

            public Criteria andWithOptionGreaterThan(Integer value) {
                  addCriterion("with_option >", value, "withOption");
                  return (Criteria) this;
            }

            public Criteria andWithOptionGreaterThanOrEqualTo(Integer value) {
                  addCriterion("with_option >=", value, "withOption");
                  return (Criteria) this;
            }

            public Criteria andWithOptionLessThan(Integer value) {
                  addCriterion("with_option <", value, "withOption");
                  return (Criteria) this;
            }

            public Criteria andWithOptionLessThanOrEqualTo(Integer value) {
                  addCriterion("with_option <=", value, "withOption");
                  return (Criteria) this;
            }

            public Criteria andWithOptionIn(List<Integer> values) {
                  addCriterion("with_option in", values, "withOption");
                  return (Criteria) this;
            }

            public Criteria andWithOptionNotIn(List<Integer> values) {
                  addCriterion("with_option not in", values, "withOption");
                  return (Criteria) this;
            }

            public Criteria andWithOptionBetween(Integer value1, Integer value2) {
                  addCriterion("with_option between", value1, value2, "withOption");
                  return (Criteria) this;
            }

            public Criteria andWithOptionNotBetween(Integer value1, Integer value2) {
                  addCriterion("with_option not between", value1, value2, "withOption");
                  return (Criteria) this;
            }

            public Criteria andCreateUserIsNull() {
                  addCriterion("create_user is null");
                  return (Criteria) this;
            }

            public Criteria andCreateUserIsNotNull() {
                  addCriterion("create_user is not null");
                  return (Criteria) this;
            }

            public Criteria andCreateUserEqualTo(String value) {
                  addCriterion("create_user =", value, "createUser");
                  return (Criteria) this;
            }

            public Criteria andCreateUserNotEqualTo(String value) {
                  addCriterion("create_user <>", value, "createUser");
                  return (Criteria) this;
            }

            public Criteria andCreateUserGreaterThan(String value) {
                  addCriterion("create_user >", value, "createUser");
                  return (Criteria) this;
            }

            public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
                  addCriterion("create_user >=", value, "createUser");
                  return (Criteria) this;
            }

            public Criteria andCreateUserLessThan(String value) {
                  addCriterion("create_user <", value, "createUser");
                  return (Criteria) this;
            }

            public Criteria andCreateUserLessThanOrEqualTo(String value) {
                  addCriterion("create_user <=", value, "createUser");
                  return (Criteria) this;
            }

            public Criteria andCreateUserLike(String value) {
                  addCriterion("create_user like", value, "createUser");
                  return (Criteria) this;
            }

            public Criteria andCreateUserNotLike(String value) {
                  addCriterion("create_user not like", value, "createUser");
                  return (Criteria) this;
            }

            public Criteria andCreateUserIn(List<String> values) {
                  addCriterion("create_user in", values, "createUser");
                  return (Criteria) this;
            }

            public Criteria andCreateUserNotIn(List<String> values) {
                  addCriterion("create_user not in", values, "createUser");
                  return (Criteria) this;
            }

            public Criteria andCreateUserBetween(String value1, String value2) {
                  addCriterion("create_user between", value1, value2, "createUser");
                  return (Criteria) this;
            }

            public Criteria andCreateUserNotBetween(String value1, String value2) {
                  addCriterion("create_user not between", value1, value2, "createUser");
                  return (Criteria) this;
            }
      }

      /**
       * This class was generated by MyBatis Generator.
       * This class corresponds to the database table login_user
       *
       * @mbggenerated do_not_delete_during_merge
       */
      public static class Criteria extends GeneratedCriteria {

            protected Criteria() {
                  super();
            }
      }

      /**
       * This class was generated by MyBatis Generator.
       * This class corresponds to the database table login_user
       *
       * @mbggenerated
       */
      public static class Criterion {
            private String condition;

            private Object value;

            private Object secondValue;

            private boolean noValue;

            private boolean singleValue;

            private boolean betweenValue;

            private boolean listValue;

            private String typeHandler;

            public String getCondition() {
                  return condition;
            }

            public Object getValue() {
                  return value;
            }

            public Object getSecondValue() {
                  return secondValue;
            }

            public boolean isNoValue() {
                  return noValue;
            }

            public boolean isSingleValue() {
                  return singleValue;
            }

            public boolean isBetweenValue() {
                  return betweenValue;
            }

            public boolean isListValue() {
                  return listValue;
            }

            public String getTypeHandler() {
                  return typeHandler;
            }

            protected Criterion(String condition) {
                  super();
                  this.condition = condition;
                  this.typeHandler = null;
                  this.noValue = true;
            }

            protected Criterion(String condition, Object value, String typeHandler) {
                  super();
                  this.condition = condition;
                  this.value = value;
                  this.typeHandler = typeHandler;
                  if (value instanceof List<?>) {
                        this.listValue = true;
                  } else {
                        this.singleValue = true;
                  }
            }

            protected Criterion(String condition, Object value) {
                  this(condition, value, null);
            }

            protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
                  super();
                  this.condition = condition;
                  this.value = value;
                  this.secondValue = secondValue;
                  this.typeHandler = typeHandler;
                  this.betweenValue = true;
            }

            protected Criterion(String condition, Object value, Object secondValue) {
                  this(condition, value, secondValue, null);
            }
      }
}